import { Tenant, User, Wallet, Category, Transaction, SavingsGoal, SavingsContribution, VisibilityRule, AuditLog } from '@/types';

export const initialTenants: Tenant[] = [
  {
    id: 't-household',
    name: 'Keluarga Utama',
    type: 'household',
    currency: 'IDR',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 't-personal',
    name: 'Dompet Pribadi Ilham',
    type: 'personal',
    currency: 'IDR',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 't-org',
    name: 'Komunitas & Tim Kreatif',
    type: 'organization',
    currency: 'IDR',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];

export const initialUsers: User[] = [
  {
    id: 'u-superadmin',
    email: 'superadmin@arthaflow.id',
    name: 'Ilham (Superadmin)',
    role: 'superadmin',
    tenant_id: 't-household',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'u-admin-household',
    email: 'admin.keluarga@arthaflow.id',
    name: 'Budi Santoso (Admin)',
    role: 'admin',
    tenant_id: 't-household',
    created_at: '2026-01-02T00:00:00Z',
  },
  {
    id: 'u-partner-household',
    email: 'siti.partner@arthaflow.id',
    name: 'Siti Rahma (Partner/User)',
    role: 'user',
    tenant_id: 't-household',
    created_at: '2026-01-03T00:00:00Z',
  },
];

export const initialWallets: Wallet[] = [
  {
    id: 'w-bca',
    tenant_id: 't-household',
    name: 'BCA Utama Keluarga',
    type: 'bank',
    balance: 24500000,
    account_number: '8830192841',
    color: '#3b82f6',
    icon: 'landmark',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'w-mandiri',
    tenant_id: 't-household',
    name: 'Mandiri Operasional',
    type: 'bank',
    balance: 12800000,
    account_number: '137001928374',
    color: '#eab308',
    icon: 'credit-card',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'w-gopay',
    tenant_id: 't-household',
    name: 'GoPay / OVO Bersama',
    type: 'e-wallet',
    balance: 1450000,
    account_number: '081234567890',
    color: '#06b6d4',
    icon: 'smartphone',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'w-cash',
    tenant_id: 't-household',
    name: 'Brankas Tunai Rumah',
    type: 'cash',
    balance: 3200000,
    color: '#10b981',
    icon: 'wallet',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const initialCategories: Category[] = [
  {
    id: 'c-gaji',
    tenant_id: 't-household',
    name: 'Gaji & Pendapatan Pokok',
    type: 'income',
    icon: 'badge-dollar-sign',
    color: '#10b981',
    budget_limit: 0,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c-bonus',
    tenant_id: 't-household',
    name: 'Bonus & Side Project',
    type: 'income',
    icon: 'sparkles',
    color: '#06b6d4',
    budget_limit: 0,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c-belanja',
    tenant_id: 't-household',
    name: 'Belanja Dapur & Pokok',
    type: 'expense',
    icon: 'shopping-cart',
    color: '#f43f5e',
    budget_limit: 6000000,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c-tagihan',
    tenant_id: 't-household',
    name: 'Listrik, Air & Internet',
    type: 'expense',
    icon: 'zap',
    color: '#fbbf24',
    budget_limit: 2000000,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c-pendidikan',
    tenant_id: 't-household',
    name: 'Pendidikan & Kursus',
    type: 'expense',
    icon: 'graduation-cap',
    color: '#8b5cf6',
    budget_limit: 3500000,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c-hiburan',
    tenant_id: 't-household',
    name: 'Hiburan & Liburan',
    type: 'expense',
    icon: 'film',
    color: '#ec4899',
    budget_limit: 2500000,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c-kesehatan',
    tenant_id: 't-household',
    name: 'Kesehatan & Obat',
    type: 'expense',
    icon: 'heart-pulse',
    color: '#14b8a6',
    budget_limit: 1500000,
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const initialSavingsGoals: SavingsGoal[] = [
  {
    id: 'sg-darurat',
    tenant_id: 't-household',
    name: 'Dana Darurat 6 Bulan',
    target_amount: 50000000,
    current_amount: 35000000,
    deadline: '2026-12-31',
    category: 'Keamanan Finansial',
    color: '#10b981',
    wallet_id: 'w-bca',
    is_completed: false,
    notes: 'Prioritas utama keluarga',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-10-01T00:00:00Z',
  },
  {
    id: 'sg-qurban',
    tenant_id: 't-household',
    name: 'Tabungan Qurban & Idul Adha',
    target_amount: 7000000,
    current_amount: 7000000,
    deadline: '2026-06-15',
    category: 'Ibadah',
    color: '#3b82f6',
    wallet_id: 'w-mandiri',
    is_completed: true,
    notes: 'Target sudah terpenuhi',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-06-10T00:00:00Z',
  },
  {
    id: 'sg-liburan',
    tenant_id: 't-household',
    name: 'Liburan Akhir Tahun ke Jepang',
    target_amount: 25000000,
    current_amount: 14200000,
    deadline: '2026-12-15',
    category: 'Rekreasi',
    color: '#8b5cf6',
    wallet_id: 'w-mandiri',
    is_completed: false,
    notes: 'Tiket & akomodasi keluarga',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-10-02T00:00:00Z',
  },
];

export const initialContributions: SavingsContribution[] = [
  {
    id: 'sc-1',
    tenant_id: 't-household',
    savings_goal_id: 'sg-darurat',
    user_id: 'u-admin-household',
    amount: 5000000,
    date: '2026-09-01',
    notes: 'Alokasi dari gaji September',
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'sc-2',
    tenant_id: 't-household',
    savings_goal_id: 'sg-liburan',
    user_id: 'u-partner-household',
    amount: 2000000,
    date: '2026-09-15',
    notes: 'Setoran tabungan tiket',
    created_at: '2026-09-15T14:30:00Z',
  },
  {
    id: 'sc-3',
    tenant_id: 't-household',
    savings_goal_id: 'sg-darurat',
    user_id: 'u-admin-household',
    amount: 3000000,
    date: '2026-10-02',
    notes: 'Alokasi awal Oktober',
    created_at: '2026-10-02T09:00:00Z',
  },
];

export const initialTransactions: Transaction[] = [
  {
    id: 'tx-1',
    tenant_id: 't-household',
    user_id: 'u-admin-household',
    user_name: 'Budi Santoso (Admin)',
    type: 'income',
    amount: 22000000,
    wallet_id: 'w-bca',
    category_id: 'c-gaji',
    category_name: 'Gaji & Pendapatan Pokok',
    date: '2026-10-01',
    notes: 'Gaji Bulanan Oktober 2026',
    created_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'tx-2',
    tenant_id: 't-household',
    user_id: 'u-partner-household',
    user_name: 'Siti Rahma (Partner/User)',
    type: 'income',
    amount: 4500000,
    wallet_id: 'w-mandiri',
    category_id: 'c-bonus',
    category_name: 'Bonus & Side Project',
    date: '2026-10-02',
    notes: 'Hasil freelance desain UI',
    created_at: '2026-10-02T11:00:00Z',
  },
  {
    id: 'tx-3',
    tenant_id: 't-household',
    user_id: 'u-partner-household',
    user_name: 'Siti Rahma (Partner/User)',
    type: 'expense',
    amount: 1450000,
    wallet_id: 'w-mandiri',
    category_id: 'c-belanja',
    category_name: 'Belanja Dapur & Pokok',
    date: '2026-10-02',
    notes: 'Belanja bulanan supermarket',
    created_at: '2026-10-02T15:30:00Z',
  },
  {
    id: 'tx-4',
    tenant_id: 't-household',
    user_id: 'u-admin-household',
    user_name: 'Budi Santoso (Admin)',
    type: 'expense',
    amount: 850000,
    wallet_id: 'w-bca',
    category_id: 'c-tagihan',
    category_name: 'Listrik, Air & Internet',
    date: '2026-10-03',
    notes: 'Tagihan Listrik PLN & Indihome',
    created_at: '2026-10-03T10:15:00Z',
  },
  {
    id: 'tx-5',
    tenant_id: 't-household',
    user_id: 'u-partner-household',
    user_name: 'Siti Rahma (Partner/User)',
    type: 'expense',
    amount: 320000,
    wallet_id: 'w-gopay',
    category_id: 'c-hiburan',
    category_name: 'Hiburan & Liburan',
    date: '2026-10-04',
    notes: 'Makan malam akhir pekan keluarga',
    created_at: '2026-10-04T19:00:00Z',
  },
  {
    id: 'tx-6',
    tenant_id: 't-household',
    user_id: 'u-admin-household',
    user_name: 'Budi Santoso (Admin)',
    type: 'transfer',
    amount: 1000000,
    wallet_id: 'w-bca',
    target_wallet_id: 'w-gopay',
    date: '2026-10-03',
    notes: 'Top-up e-wallet operasional',
    created_at: '2026-10-03T14:00:00Z',
  },
  {
    id: 'tx-7',
    tenant_id: 't-household',
    user_id: 'u-admin-household',
    user_name: 'Budi Santoso (Admin)',
    type: 'expense',
    amount: 1200000,
    wallet_id: 'w-bca',
    category_id: 'c-pendidikan',
    category_name: 'Pendidikan & Kursus',
    date: '2026-09-20',
    notes: 'Biaya les kursus anak',
    created_at: '2026-09-20T09:00:00Z',
  },
];

export const initialVisibilityRules: VisibilityRule[] = [
  {
    id: 'vr-partner',
    tenant_id: 't-household',
    target_user_id: 'u-partner-household',
    allowed_wallet_ids: ['w-bca', 'w-mandiri', 'w-gopay', 'w-cash'],
    allowed_category_ids: ['c-gaji', 'c-bonus', 'c-belanja', 'c-tagihan', 'c-pendidikan', 'c-hiburan', 'c-kesehatan'],
    can_view_all_transactions: true,
    can_view_savings: true,
    can_view_analytics: true,
    can_export_reports: true,
    can_manage_categories: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-10-01T00:00:00Z',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    tenant_id: 't-household',
    user_id: 'u-admin-household',
    user_name: 'Budi Santoso',
    user_role: 'admin',
    action: 'CREATE',
    entity: 'transaction',
    details: 'Mencatat pemasukan Gaji Pokok sebesar Rp 22.000.000',
    ip_address: '180.252.12.90',
    created_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'log-2',
    tenant_id: 't-household',
    user_id: 'u-partner-household',
    user_name: 'Siti Rahma',
    user_role: 'user',
    action: 'CREATE',
    entity: 'transaction',
    details: 'Mencatat pengeluaran Belanja Dapur Rp 1.450.000',
    ip_address: '180.252.12.91',
    created_at: '2026-10-02T15:30:00Z',
  },
  {
    id: 'log-3',
    tenant_id: 't-household',
    user_id: 'u-admin-household',
    user_name: 'Budi Santoso',
    user_role: 'admin',
    action: 'CONFIG_CHANGE',
    entity: 'visibility',
    details: 'Memperbarui aturan hak visibilitas data untuk Siti Rahma (User)',
    ip_address: '180.252.12.90',
    created_at: '2026-10-01T12:00:00Z',
  },
];
